# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-03-01 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200228_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_md',
            field=models.BooleanField(default=False, verbose_name='是否Markdown语法'),
        ),
    ]
